#!/usr/bin/with-contenv bash

source /root/.bashrc
echo -e "${BLUE}--- Caching Laravel configuration ---${NC}"
cd /app/

# Update config and routes cache
## must execute with application permissions - as nginx user
xargs -0 exec s6-setuidgid nginx sh -c <<EOF
  php artisan cache:clear
  php artisan config:cache
  php artisan route:cache
  php artisan api:cache
EOF

chown -R nginx:nginx storage
chown root:nginx /tmp
chmod 775 /tmp

php artisan up
