<?php

namespace App\Http\Middleware;

use Closure;
use Illuminate\Http\Request;
use Illuminate\Support\Str;
use URL;

/**
 * All URLs, generated by API or CLI tools must point to frontend
 */
class ForceUrl
{
    /**
     * Handle an incoming request.
     *
     * @param Request $request current request
     * @param Closure $next next middleware function
     *
     * @return mixed
     */
    public function handle(Request $request, Closure $next)
    {
        $frontendUrl = config('app.url');
        URL::forceRootUrl(config('app.url'));
        if (Str::startsWith($frontendUrl, 'http:')) {
            URL::forceScheme('http');
        }
        return $next($request);
    }
}
