<?php

use Illuminate\Database\Migrations\Migration;

/**
 * Bulk create tables.
 */
class CreateTables extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up(): void
    {
        $queries = $this->parseMultiSqlFile(__DIR__ . '/baseline/db_create.sql');
        foreach ($queries as $query) {
            DB::statement($query);
        }
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down(): void
    {
        $queries = $this->parseMultiSqlFile(__DIR__ . '/baseline/db_drop.sql');
        foreach ($queries as $query) {
            DB::statement($query);
        }
    }

    /**
     * Parse sql file generated by DeZign for Databases for array of queries.
     *
     * @param string $fileName Sql filename to parse
     *
     * @return array Sql queries
     */
    private function parseMultiSqlFile(string $fileName): array
    {
        $content = file_get_contents($fileName);
        return array_filter(explode(";\n", $content));
    }
}
